# Generated by Django 3.1.3 on 2021-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweetphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
